# 경기도 지역 데이터 — 31개 시·군 / 일반구 / 생활권 / 지하철역 / 읍면동
# 메뉴·URL에는 키워드("출장마사지")를 넣지 않는다. slug 는 영문 지역명만 사용한다.

# 권역
REGION_GROUPS = {
    "south": {
        "name": "경기남부",
        "slug": "south",
        "cities": ["suwon", "yongin", "hwaseong", "seongnam", "bucheon", "ansan",
                   "pyeongtaek", "anyang", "siheung", "gimpo", "gwangju-si", "hanam",
                   "gwangmyeong", "gunpo", "osan", "icheon", "anseong", "uiwang",
                   "yangpyeong", "yeoju", "gwacheon"],
    },
    "north": {
        "name": "경기북부",
        "slug": "north",
        "cities": ["goyang", "namyangju", "paju", "uijeongbu", "yangju",
                   "guri", "pocheon", "dongducheon", "gapyeong", "yeoncheon"],
    },
}

# 31개 시·군
# car=True  → 역세권보다 차량 이동 기준·추가 이동비 확인이 중요한 도농복합/외곽
CITIES = {
    # ===== 경기남부 =====
    "suwon": {
        "name": "수원시", "short": "수원", "group": "south", "wiki": "수원시",
        "gu": [("jangan-gu", "장안구"), ("gwonseon-gu", "권선구"),
               ("paldal-gu", "팔달구"), ("yeongtong-gu", "영통구")],
        "life": ["수원역·매산", "인계동·수원시청", "영통·망포", "광교·원천", "호매실·금곡"],
        "stations": ["수원역", "화서역", "성균관대역", "영통역", "수원시청역", "매교역", "광교중앙역"],
        "nearby": ["yongin", "hwaseong", "anyang", "uiwang", "osan"],
        "intro": "수원시는 경기남부 행정·교통의 중심으로, 수원역 상권과 광교·영통 신도시 생활권이 뚜렷하게 나뉩니다.",
    },
    "yongin": {
        "name": "용인시", "short": "용인", "group": "south", "wiki": "용인시",
        "gu": [("cheoin-gu", "처인구"), ("giheung-gu", "기흥구"), ("suji-gu", "수지구")],
        "life": ["수지구청·풍덕천", "죽전·보정", "동천·성복", "기흥역·구갈", "동백·어정"],
        "stations": ["수지구청역", "성복역", "상현역", "죽전역", "보정역", "기흥역", "동백역"],
        "nearby": ["suwon", "seongnam", "hwaseong", "gwangju-si", "anseong"],
        "intro": "용인시는 수지·기흥의 도심 생활권과 처인구의 도농복합 생활권이 함께 있어 위치별 이동 기준이 다릅니다.",
    },
    "hwaseong": {
        "name": "화성시", "short": "화성", "group": "south", "wiki": "화성시",
        "gu": [],
        "life": ["동탄신도시", "병점·진안", "봉담", "향남", "남양·새솔동"],
        "stations": ["동탄역", "병점역", "서동탄역", "어천역"],
        "nearby": ["suwon", "osan", "pyeongtaek", "yongin", "ansan"],
        "intro": "화성시는 동탄신도시 같은 대규모 아파트 생활권과 봉담·향남 등 차량 이동 중심 생활권이 함께 있습니다.",
    },
    "seongnam": {
        "name": "성남시", "short": "성남", "group": "south", "wiki": "성남시",
        "gu": [("sujeong-gu", "수정구"), ("jungwon-gu", "중원구"), ("bundang-gu", "분당구")],
        "life": ["분당·서현", "정자·수내", "판교·백현", "야탑·이매", "모란·수진"],
        "stations": ["판교역", "정자역", "미금역", "수내역", "서현역", "야탑역", "모란역"],
        "nearby": ["yongin", "gwangju-si", "hanam", "gwacheon", "suwon"],
        "intro": "성남시는 판교 업무지구와 분당 주거 생활권, 구도심 수정·중원 생활권이 한 도시 안에 공존합니다.",
    },
    "bucheon": {
        "name": "부천시", "short": "부천", "group": "south", "wiki": "부천시",
        "gu": [("wonmi-gu", "원미구"), ("sosa-gu", "소사구"), ("ojeong-gu", "오정구")],
        "life": ["부천역·상동", "중동신도시", "송내", "역곡·소사", "원종·오정"],
        "stations": ["부천역", "송내역", "역곡역", "소사역", "신중동역", "부천시청역", "상동역"],
        "nearby": ["siheung", "gwangmyeong", "gimpo", "ansan"],
        "intro": "부천시는 부천역·중동·상동을 잇는 고밀도 도심 생활권으로, 역세권 접근성이 매우 좋은 지역입니다.",
    },
    "ansan": {
        "name": "안산시", "short": "안산", "group": "south", "wiki": "안산시",
        "gu": [("sangnok-gu", "상록구"), ("danwon-gu", "단원구")],
        "life": ["중앙·고잔", "상록수·본오", "초지·원곡", "선부", "안산역"],
        "stations": ["중앙역", "고잔역", "초지역", "안산역", "상록수역", "한대앞역", "선부역"],
        "nearby": ["siheung", "hwaseong", "gunpo", "gwangmyeong"],
        "intro": "안산시는 중앙·고잔 중심권과 상록수·본오 생활권, 시화·반월의 산업 생활권으로 나뉩니다.",
    },
    "pyeongtaek": {
        "name": "평택시", "short": "평택", "group": "south", "wiki": "평택시", "car": True,
        "gu": [],
        "life": ["평택역·소사벌", "고덕국제신도시", "송탄·서정리", "지제역", "안중·포승"],
        "stations": ["평택역", "평택지제역", "서정리역", "송탄역", "진위역"],
        "nearby": ["osan", "hwaseong", "anseong"],
        "intro": "평택시는 평택역·소사벌 도심과 고덕국제신도시, 안중·포승 등 차량 이동 중심권이 넓게 분포합니다.",
    },
    "anyang": {
        "name": "안양시", "short": "안양", "group": "south", "wiki": "안양시",
        "gu": [("manan-gu", "만안구"), ("dongan-gu", "동안구")],
        "life": ["안양역·일번가", "범계·평촌", "인덕원·관양", "석수·관악", "비산·명학"],
        "stations": ["안양역", "명학역", "석수역", "관악역", "범계역", "평촌역", "인덕원역"],
        "nearby": ["gwacheon", "uiwang", "gunpo", "gwangmyeong", "suwon"],
        "intro": "안양시는 안양역 일번가 상권과 범계·평촌 학원가 생활권을 중심으로 유동 인구가 많은 도시입니다.",
    },
    "siheung": {
        "name": "시흥시", "short": "시흥", "group": "south", "wiki": "시흥시",
        "gu": [],
        "life": ["배곧", "정왕·오이도", "시흥시청·장현", "은계", "목감·능곡"],
        "stations": ["오이도역", "정왕역", "월곶역", "시흥시청역", "시흥능곡역", "신천역"],
        "nearby": ["ansan", "gwangmyeong", "bucheon", "gunpo"],
        "intro": "시흥시는 배곧신도시와 정왕·오이도 생활권, 은계·목감 택지지구가 빠르게 성장하는 지역입니다.",
    },
    "gimpo": {
        "name": "김포시", "short": "김포", "group": "south", "wiki": "김포시",
        "gu": [],
        "life": ["구래·마산", "장기·운양", "풍무·사우", "고촌", "통진·양촌"],
        "stations": ["고촌역", "풍무역", "사우역", "운양역", "장기역", "구래역", "양촌역"],
        "nearby": ["bucheon", "goyang", "gwangmyeong"],
        "intro": "김포시는 한강신도시(구래·장기·운양)와 풍무·사우 생활권을 김포골드라인이 이어 주는 도시입니다.",
    },
    "gwangju-si": {
        "name": "광주시", "short": "광주", "group": "south", "wiki": "광주시 (경기도)", "car": True,
        "gu": [],
        "life": ["경안·쌍령", "태전", "오포", "초월·곤지암", "퇴촌"],
        "stations": ["경기광주역", "초월역", "곤지암역", "삼동역"],
        "nearby": ["seongnam", "yongin", "hanam", "icheon", "yeoju"],
        "intro": "광주시는 경안·태전 도심과 오포·곤지암 등 차량 이동 중심 생활권이 넓게 펼쳐진 도농복합 도시입니다.",
    },
    "hanam": {
        "name": "하남시", "short": "하남", "group": "south", "wiki": "하남시",
        "gu": [],
        "life": ["미사강변도시", "덕풍·신장", "감일", "위례", "창우·천현"],
        "stations": ["미사역", "하남풍산역", "하남시청역", "하남검단산역"],
        "nearby": ["seongnam", "guri", "namyangju", "gwangju-si"],
        "intro": "하남시는 미사강변도시와 감일·위례 신도시를 중심으로 5호선 연장과 함께 빠르게 성장한 지역입니다.",
    },
    "gwangmyeong": {
        "name": "광명시", "short": "광명", "group": "south", "wiki": "광명시",
        "gu": [],
        "life": ["철산·광명사거리", "하안", "소하·일직", "광명역", "학온"],
        "stations": ["철산역", "광명사거리역", "광명역"],
        "nearby": ["bucheon", "anyang", "siheung", "gunpo"],
        "intro": "광명시는 철산·광명사거리 도심과 KTX 광명역 일직·소하 생활권으로 서울 인접 생활권을 형성합니다.",
    },
    "gunpo": {
        "name": "군포시", "short": "군포", "group": "south", "wiki": "군포시",
        "gu": [],
        "life": ["산본신도시", "금정", "군포·당정", "부곡·대야미", "송정"],
        "stations": ["산본역", "금정역", "군포역", "당정역", "대야미역", "수리산역"],
        "nearby": ["anyang", "uiwang", "ansan", "suwon"],
        "intro": "군포시는 산본신도시 주거 생활권과 금정역 환승 거점을 중심으로 한 컴팩트한 생활권을 이룹니다.",
    },
    "osan": {
        "name": "오산시", "short": "오산", "group": "south", "wiki": "오산시",
        "gu": [],
        "life": ["오산역·중앙", "오산대역·세교", "세마", "대원", "신장"],
        "stations": ["오산역", "오산대역", "세마역"],
        "nearby": ["hwaseong", "pyeongtaek", "suwon"],
        "intro": "오산시는 오산역 중심 상권과 세교신도시 주거 생활권을 1호선 축으로 이어 가는 도시입니다.",
    },
    "icheon": {
        "name": "이천시", "short": "이천", "group": "south", "wiki": "이천시", "car": True,
        "gu": [],
        "life": ["이천역·창전", "증포·중리", "부발", "마장·신둔", "장호원"],
        "stations": ["이천역", "부발역", "신둔도예촌역"],
        "nearby": ["yongin", "gwangju-si", "yeoju", "anseong"],
        "intro": "이천시는 이천역·창전 도심과 부발·마장 등 차량 이동 기준 생활권이 함께 있는 도농복합 도시입니다.",
    },
    "anseong": {
        "name": "안성시", "short": "안성", "group": "south", "wiki": "안성시", "car": True,
        "gu": [],
        "life": ["안성·공도", "대덕", "원곡", "보개·죽산", "일죽"],
        "stations": [],
        "nearby": ["pyeongtaek", "yongin", "icheon"],
        "intro": "안성시는 역세권보다 차량 이동 기준이 중요한 도농복합 도시로, 공도·안성 도심권을 중심으로 안내합니다.",
    },
    "uiwang": {
        "name": "의왕시", "short": "의왕", "group": "south", "wiki": "의왕시",
        "gu": [],
        "life": ["의왕역·부곡", "내손·포일", "고천·오전", "청계", "백운밸리"],
        "stations": ["의왕역"],
        "nearby": ["anyang", "suwon", "gunpo", "gwacheon"],
        "intro": "의왕시는 의왕역·부곡 생활권과 내손·포일, 백운밸리 신주거지가 인덕원 인접권으로 이어집니다.",
    },
    "yangpyeong": {
        "name": "양평군", "short": "양평", "group": "south", "wiki": "양평군", "car": True,
        "gu": [],
        "life": ["양평읍", "용문", "양서·서종", "강상·강하", "옥천·지평"],
        "stations": ["양평역", "용문역", "양수역", "국수역"],
        "nearby": ["yeoju", "gwangju-si", "gapyeong"],
        "intro": "양평군은 경의중앙선 역세권과 함께 차량 이동·추가 이동비 확인이 중요한 외곽 생활권이 넓습니다.",
    },
    "yeoju": {
        "name": "여주시", "short": "여주", "group": "south", "wiki": "여주시", "car": True,
        "gu": [],
        "life": ["여주역·여주동", "가남", "오학", "흥천·금사", "대신"],
        "stations": ["여주역", "세종대왕릉역", "가남역"],
        "nearby": ["icheon", "yangpyeong", "gwangju-si"],
        "intro": "여주시는 여주역·가남 생활권을 중심으로 차량 이동 기준과 추가 이동비 확인이 중요한 지역입니다.",
    },
    "gwacheon": {
        "name": "과천시", "short": "과천", "group": "south", "wiki": "과천시",
        "gu": [],
        "life": ["과천·정부청사", "별양·부림", "문원·갈현", "지식정보타운", "중앙동"],
        "stations": ["과천역", "정부과천청사역", "대공원역", "경마공원역", "선바위역"],
        "nearby": ["anyang", "seongnam", "uiwang", "gwacheon"],
        "intro": "과천시는 정부과천청사와 지식정보타운을 중심으로 한 컴팩트한 행정·주거 생활권을 이룹니다.",
    },
    # ===== 경기북부 =====
    "goyang": {
        "name": "고양시", "short": "고양", "group": "north", "wiki": "고양시",
        "gu": [("deogyang-gu", "덕양구"), ("ilsandong-gu", "일산동구"), ("ilsanseo-gu", "일산서구")],
        "life": ["일산·정발산", "마두·백석", "주엽·대화", "킨텍스·장항", "화정·행신", "삼송·원흥"],
        "stations": ["대화역", "주엽역", "정발산역", "마두역", "백석역", "화정역", "삼송역"],
        "nearby": ["paju", "gimpo", "uijeongbu", "yangju"],
        "intro": "고양시는 일산신도시(정발산·주엽·대화)와 화정·삼송 생활권이 3호선·경의중앙선으로 이어집니다.",
    },
    "namyangju": {
        "name": "남양주시", "short": "남양주", "group": "north", "wiki": "남양주시",
        "gu": [],
        "life": ["다산·별내", "진접·오남", "호평·평내", "화도·마석", "와부·덕소"],
        "stations": ["다산역", "별내역", "평내호평역", "마석역", "덕소역", "도농역", "진접역"],
        "nearby": ["guri", "uijeongbu", "gapyeong", "hanam"],
        "intro": "남양주시는 다산·별내 신도시와 호평·평내, 화도·마석 등 생활권이 넓게 분산된 도시입니다.",
    },
    "paju": {
        "name": "파주시", "short": "파주", "group": "north", "wiki": "파주시", "car": True,
        "gu": [],
        "life": ["운정신도시", "야당·금릉", "금촌", "문산", "교하·탄현"],
        "stations": ["운정역", "야당역", "금릉역", "금촌역", "문산역"],
        "nearby": ["goyang", "yangju", "gimpo"],
        "intro": "파주시는 운정신도시와 금촌·문산 생활권을 경의중앙선·GTX 축으로 이어 가는 북부 거점 도시입니다.",
    },
    "uijeongbu": {
        "name": "의정부시", "short": "의정부", "group": "north", "wiki": "의정부시",
        "gu": [],
        "life": ["의정부역·중앙", "회룡·호원", "신곡·민락", "금오·녹양", "고산·탑석"],
        "stations": ["의정부역", "회룡역", "망월사역", "가능역", "녹양역", "탑석역"],
        "nearby": ["yangju", "namyangju", "pocheon", "guri"],
        "intro": "의정부시는 의정부역 중심 상권과 민락·신곡 주거 생활권을 1호선·의정부경전철이 이어 줍니다.",
    },
    "yangju": {
        "name": "양주시", "short": "양주", "group": "north", "wiki": "양주시", "car": True,
        "gu": [],
        "life": ["옥정신도시", "회천·덕정", "고읍", "양주역·백석", "광적·장흥"],
        "stations": ["양주역", "덕계역", "덕정역"],
        "nearby": ["uijeongbu", "dongducheon", "pocheon", "paju"],
        "intro": "양주시는 옥정·회천 신도시와 덕정·양주역 생활권을 중심으로 차량 이동 기준 확인이 함께 필요합니다.",
    },
    "guri": {
        "name": "구리시", "short": "구리", "group": "north", "wiki": "구리시",
        "gu": [],
        "life": ["구리역·인창", "수택·교문", "갈매", "동구릉·토평"],
        "stations": ["구리역", "갈매역", "장자호수공원역"],
        "nearby": ["namyangju", "uijeongbu", "hanam"],
        "intro": "구리시는 구리역·인창 상권과 수택·교문 주거 생활권, 갈매지구가 콤팩트하게 이어진 도시입니다.",
    },
    "pocheon": {
        "name": "포천시", "short": "포천", "group": "north", "wiki": "포천시", "car": True,
        "gu": [],
        "life": ["포천·소흘", "송우리·선단", "일동·이동", "영북·가산"],
        "stations": [],
        "nearby": ["uijeongbu", "yangju", "gapyeong"],
        "intro": "포천시는 역세권보다 차량 이동 기준이 중요한 외곽 도시로, 소흘·송우리 생활권을 중심으로 안내합니다.",
    },
    "dongducheon": {
        "name": "동두천시", "short": "동두천", "group": "north", "wiki": "동두천시",
        "gu": [],
        "life": ["동두천중앙·지행", "보산·생연", "소요·상패"],
        "stations": ["동두천중앙역", "지행역", "보산역", "동두천역", "소요산역"],
        "nearby": ["yangju", "yeoncheon", "pocheon"],
        "intro": "동두천시는 동두천중앙·지행 생활권을 1호선 축으로 이어 가는 경기 북단 거점 도시입니다.",
    },
    "gapyeong": {
        "name": "가평군", "short": "가평", "group": "north", "wiki": "가평군", "car": True,
        "gu": [],
        "life": ["가평읍", "청평", "설악", "상면·조종"],
        "stations": ["가평역", "청평역", "상천역"],
        "nearby": ["namyangju", "yangpyeong", "pocheon"],
        "intro": "가평군은 경춘선 역세권과 함께 차량 이동·사전 예약·추가 이동비 확인이 중요한 외곽 생활권입니다.",
    },
    "yeoncheon": {
        "name": "연천군", "short": "연천", "group": "north", "wiki": "연천군", "car": True,
        "gu": [],
        "life": ["연천읍", "전곡", "청산·군남", "신서·백학"],
        "stations": ["연천역", "전곡역"],
        "nearby": ["dongducheon", "pocheon"],
        "intro": "연천군은 차량 이동 기준과 사전 예약, 추가 이동비 확인이 특히 중요한 경기 최북단 외곽 지역입니다.",
    },
}

# 일반구별 대표 동 (구 페이지 본문·동 페이지 생성에 사용)
GU_DONG = {
    ("suwon", "jangan-gu"): ["정자동", "율전동", "조원동", "송죽동", "영화동"],
    ("suwon", "gwonseon-gu"): ["권선동", "세류동", "곡선동", "금곡동", "호매실동"],
    ("suwon", "paldal-gu"): ["인계동", "매산동", "우만동", "지동", "행궁동"],
    ("suwon", "yeongtong-gu"): ["영통동", "망포동", "매탄동", "광교동", "원천동"],
    ("yongin", "cheoin-gu"): ["역북동", "김량장동", "삼가동", "포곡읍", "모현읍"],
    ("yongin", "giheung-gu"): ["기흥동", "구갈동", "신갈동", "보정동", "동백동"],
    ("yongin", "suji-gu"): ["풍덕천동", "죽전동", "동천동", "성복동", "상현동"],
    ("seongnam", "sujeong-gu"): ["신흥동", "수진동", "단대동", "산성동", "위례동"],
    ("seongnam", "jungwon-gu"): ["성남동", "은행동", "상대원동", "중앙동", "금광동"],
    ("seongnam", "bundang-gu"): ["정자동", "서현동", "수내동", "야탑동", "판교동", "백현동"],
    ("bucheon", "wonmi-gu"): ["중동", "상동", "심곡동", "춘의동", "약대동"],
    ("bucheon", "sosa-gu"): ["소사본동", "괴안동", "역곡동", "송내동", "심곡본동"],
    ("bucheon", "ojeong-gu"): ["원종동", "오정동", "고강동", "성곡동"],
    ("ansan", "sangnok-gu"): ["본오동", "사동", "월피동", "이동", "성포동"],
    ("ansan", "danwon-gu"): ["고잔동", "중앙동", "초지동", "원곡동", "선부동"],
    ("anyang", "manan-gu"): ["안양동", "석수동", "박달동", "명학동"],
    ("anyang", "dongan-gu"): ["비산동", "관양동", "평촌동", "호계동", "범계동"],
    ("goyang", "deogyang-gu"): ["화정동", "행신동", "삼송동", "원흥동", "지축동"],
    ("goyang", "ilsandong-gu"): ["장항동", "마두동", "백석동", "정발산동", "식사동"],
    ("goyang", "ilsanseo-gu"): ["주엽동", "대화동", "탄현동", "일산동", "덕이동"],
}

# 일반구가 없는 도시의 대표 동/읍·면 (동 페이지 생성에 사용)
CITY_DONG = {
    "hwaseong": ["병점동", "봉담읍", "향남읍", "남양읍", "새솔동"],
    "siheung": ["배곧동", "정왕동", "월곶동", "목감동", "은행동"],
    "gimpo": ["구래동", "장기동", "운양동", "풍무동", "사우동", "고촌읍"],
    "namyangju": ["다산동", "별내동", "호평동", "평내동", "진접읍", "화도읍"],
    "uijeongbu": ["의정부동", "호원동", "신곡동", "민락동", "고산동", "녹양동"],
    "hanam": ["풍산동", "덕풍동", "신장동", "감일동", "위례동"],
    "gwangmyeong": ["철산동", "광명동", "하안동", "소하동", "일직동"],
    "pyeongtaek": ["비전동", "평택동", "고덕동", "서정동", "송탄동", "안중읍"],
    "paju": ["야당동", "금촌동", "교하동", "문산읍", "탄현면"],
    "guri": ["인창동", "수택동", "교문동", "갈매동"],
    "gunpo": ["산본동", "금정동", "군포동", "당정동", "부곡동"],
    "osan": ["중앙동", "세마동", "초평동", "신장동"],
    "uiwang": ["고천동", "오전동", "부곡동", "내손동", "포일동", "청계동"],
    "gwangju-si": ["경안동", "쌍령동", "태전동", "송정동", "초월읍", "곤지암읍"],
    "icheon": ["창전동", "증포동", "중리동", "부발읍", "마장면"],
    "yongin_cheoin_eup": [],  # placeholder
}


# ===== 생활권 (1차 색인 대상) =====
# slug, name, city(slug), areas(동 리스트), stations(역 리스트), role(역할 설명)
LIFE_AREAS = [
    ("suwon-station-ingye", "수원역·인계동", "suwon",
     ["매산동", "인계동", "세류동", "권선동"], ["수원역", "매교역", "수원시청역"],
     "수원 도심 상권과 숙소·오피스텔이 밀집한 인접권으로, 방문 접근성이 가장 높은 생활권입니다."),
    ("gwanggyo-yeongtong", "광교·영통", "suwon",
     ["광교동", "원천동", "영통동", "망포동"], ["광교중앙역", "영통역", "망포역"],
     "광교 호수공원과 영통 아파트 단지를 잇는 신도시 주거 생활권입니다."),
    ("bundang-pangyo", "분당·판교", "seongnam",
     ["판교동", "삼평동", "백현동", "정자동", "서현동"], ["판교역", "정자역", "서현역"],
     "판교 업무지구와 분당 주거지·호텔을 함께 아우르는 경기남부 핵심 생활권입니다."),
    ("yatap-seohyeon", "야탑·서현", "seongnam",
     ["야탑동", "이매동", "서현동", "수내동"], ["야탑역", "서현역", "수내역"],
     "분당 중심 상권과 종합병원·터미널이 가까운 생활권입니다."),
    ("jukjeon-suji", "죽전·수지", "yongin",
     ["죽전동", "보정동", "풍덕천동", "동천동"], ["죽전역", "수지구청역", "동천역"],
     "수지구청·죽전을 잇는 용인 북부 주거 생활권입니다."),
    ("giheung-dongbaek", "기흥·동백", "yongin",
     ["기흥동", "구갈동", "신갈동", "동백동"], ["기흥역", "동백역", "보정역"],
     "기흥역 환승 거점과 동백·어정 주거 생활권을 잇는 권역입니다."),
    ("dongtan-newtown", "동탄신도시", "hwaseong",
     ["반송동", "석우동", "영천동", "청계동", "산척동"], ["동탄역"],
     "동탄1·2신도시의 대규모 아파트와 숙소 인접권을 안내하는 생활권입니다."),
    ("byeongjeom-bongdam", "병점·봉담", "hwaseong",
     ["병점동", "진안동", "봉담읍"], ["병점역", "서동탄역"],
     "병점역 상권과 봉담 택지지구를 잇는 화성 서부 생활권입니다."),
    ("pyeongtaek-station-sosabeol", "평택역·소사벌", "pyeongtaek",
     ["평택동", "비전동", "고덕동"], ["평택역", "평택지제역"],
     "평택역 상권과 소사벌·고덕 주거 생활권을 잇는 권역입니다."),
    ("bucheon-station-sangdong", "부천역·상동", "bucheon",
     ["심곡동", "중동", "상동"], ["부천역", "신중동역", "상동역"],
     "부천역 상권과 중동·상동 신도시 주거지를 잇는 고밀도 생활권입니다."),
    ("ansan-jungang-choji", "안산중앙·초지", "ansan",
     ["고잔동", "중앙동", "초지동", "원곡동"], ["중앙역", "초지역", "안산역"],
     "안산 중심 상권과 고잔·초지 주거 생활권을 잇는 권역입니다."),
    ("anyang-beomgye-pyeongchon", "안양·범계·평촌", "anyang",
     ["비산동", "관양동", "평촌동", "호계동"], ["범계역", "평촌역", "인덕원역"],
     "범계·평촌 학원가와 안양 상권을 잇는 동안구 핵심 생활권입니다."),
    ("siheung-baegot", "시흥·배곧", "siheung",
     ["배곧동", "정왕동"], ["정왕역", "오이도역", "시흥시청역"],
     "배곧신도시와 정왕·오이도 주거 생활권을 잇는 권역입니다."),
    ("gimpo-gurae", "김포·구래", "gimpo",
     ["구래동", "장기동", "운양동"], ["구래역", "장기역", "운양역"],
     "한강신도시(구래·장기·운양)의 주거 생활권을 잇는 권역입니다."),
    ("ilsan-kintex", "일산·킨텍스", "goyang",
     ["장항동", "대화동", "주엽동", "백석동"], ["대화역", "주엽역", "정발산역"],
     "킨텍스 전시장과 일산 주거지·호텔을 함께 아우르는 생활권입니다."),
    ("hwajeong-samsong", "화정·삼송", "goyang",
     ["화정동", "행신동", "삼송동", "원흥동"], ["화정역", "삼송역"],
     "화정 상권과 삼송·원흥 택지지구를 잇는 덕양구 생활권입니다."),
    ("namyangju-dasan", "남양주·다산", "namyangju",
     ["다산동", "별내동", "도농동"], ["다산역", "별내역", "도농역"],
     "다산·별내 신도시 주거 생활권을 잇는 권역입니다."),
    ("uijeongbu-station-minrak", "의정부역·민락", "uijeongbu",
     ["의정부동", "신곡동", "민락동"], ["의정부역", "탑석역"],
     "의정부역 상권과 민락·신곡 주거 생활권을 잇는 권역입니다."),
    ("paju-unjeong", "파주·운정", "paju",
     ["야당동", "금촌동", "교하동"], ["운정역", "야당역", "금촌역"],
     "운정신도시와 금촌 생활권을 잇는 파주 남부 권역입니다."),
    ("hanam-misa", "하남·미사", "hanam",
     ["풍산동", "덕풍동", "신장동"], ["미사역", "하남풍산역", "하남시청역"],
     "미사강변도시와 덕풍·신장 주거 생활권을 잇는 권역입니다."),
    ("guri-galmae", "구리·갈매", "guri",
     ["인창동", "수택동", "갈매동"], ["구리역", "갈매역"],
     "구리역 상권과 갈매지구 주거 생활권을 잇는 권역입니다."),
    ("gwangmyeong-cheolsan", "광명·철산", "gwangmyeong",
     ["철산동", "광명동", "하안동"], ["철산역", "광명사거리역"],
     "철산·광명사거리 도심 주거·상업 생활권을 잇는 권역입니다."),
    ("gunpo-sanbon", "군포·산본", "gunpo",
     ["산본동", "금정동", "당정동"], ["산본역", "금정역"],
     "산본신도시 주거 생활권과 금정 환승 거점을 잇는 권역입니다."),
    ("osan-segyo", "오산역·세교", "osan",
     ["중앙동", "세마동", "초평동"], ["오산역", "오산대역", "세마역"],
     "오산역 상권과 세교신도시 주거 생활권을 잇는 권역입니다."),
    ("uiwang-naeson", "의왕역·내손", "uiwang",
     ["고천동", "내손동", "포일동"], ["의왕역"],
     "의왕역·부곡과 내손·포일 주거 생활권을 잇는 인덕원 인접 권역입니다."),
    ("gwacheon-cheongsa", "과천·정부청사", "gwacheon",
     ["중앙동", "별양동", "부림동"], ["과천역", "정부과천청사역"],
     "정부과천청사와 지식정보타운을 중심으로 한 행정·주거 생활권입니다."),
    ("gwangju-taejeon", "경기광주·태전", "gwangju-si",
     ["경안동", "쌍령동", "태전동"], ["경기광주역", "초월역"],
     "경안 도심과 태전 택지지구를 잇는 광주 중심 생활권입니다."),
    ("icheon-bubal", "이천·부발", "icheon",
     ["창전동", "증포동", "부발읍"], ["이천역", "부발역"],
     "이천역 도심과 부발 생활권을 잇는 권역입니다."),
    ("yangpyeong-yongmun", "양평·용문", "yangpyeong",
     ["양평읍", "용문면"], ["양평역", "용문역"],
     "양평읍과 용문 생활권을 잇는, 차량 이동 기준 확인이 중요한 외곽 권역입니다."),
    ("gapyeong-cheongpyeong", "가평·청평", "gapyeong",
     ["가평읍", "청평면"], ["가평역", "청평역"],
     "가평읍·청평 생활권을 잇는, 사전 예약·추가 이동비 확인이 중요한 외곽 권역입니다."),
    ("yangju-okjeong", "양주·옥정", "yangju",
     ["옥정동", "회천동", "덕정동"], ["양주역", "덕정역"],
     "옥정·회천 신도시와 덕정 생활권을 잇는 양주 중심 권역입니다."),
    ("dongducheon-jihaeng", "동두천·지행", "dongducheon",
     ["생연동", "지행동", "보산동"], ["동두천중앙역", "지행역"],
     "동두천중앙·지행 생활권을 잇는 경기 북단 권역입니다."),
    ("outer-northeast-area", "양평·가평·연천 외곽", "yangpyeong",
     ["양평읍", "가평읍", "연천읍", "전곡읍"], ["양평역", "가평역", "전곡역"],
     "역세권이 드문 외곽 군 지역으로, 차량 이동·사전 예약·추가 이동비 확인이 가장 중요한 권역입니다."),
]

# ===== 지하철역 (역명 기준 1개 URL, 환승역도 분리하지 않음) =====
# slug, name, city(slug), lines(노선), areas(인접 동), nearby_cities(slug)
STATIONS = [
    ("suwon-station", "수원역", "suwon", ["1호선", "수인분당선"], ["매산동", "인계동", "고등동"], ["hwaseong"]),
    ("hwaseo-station", "화서역", "suwon", ["1호선"], ["화서동", "정자동"], []),
    ("suwon-city-hall-station", "수원시청역", "suwon", ["수인분당선"], ["인계동", "권선동"], []),
    ("yeongtong-station", "영통역", "suwon", ["수인분당선"], ["영통동", "망포동"], ["yongin"]),
    ("gwanggyo-jungang-station", "광교중앙역", "suwon", ["신분당선"], ["광교동", "원천동"], []),
    ("maegyo-station", "매교역", "suwon", ["수인분당선"], ["매교동", "인계동"], []),
    ("pangyo-station", "판교역", "seongnam", ["신분당선", "경강선"], ["판교동", "삼평동", "백현동"], ["yongin"]),
    ("jeongja-station", "정자역", "seongnam", ["신분당선", "수인분당선"], ["정자동", "수내동"], []),
    ("seohyeon-station", "서현역", "seongnam", ["수인분당선"], ["서현동", "이매동"], []),
    ("sunae-station", "수내역", "seongnam", ["수인분당선"], ["수내동", "정자동"], []),
    ("yatap-station", "야탑역", "seongnam", ["수인분당선"], ["야탑동", "이매동"], []),
    ("migeum-station", "미금역", "seongnam", ["신분당선", "수인분당선"], ["금곡동", "구미동"], ["yongin"]),
    ("moran-station", "모란역", "seongnam", ["수인분당선", "8호선"], ["성남동", "수진동"], []),
    ("jukjeon-station", "죽전역", "yongin", ["수인분당선"], ["죽전동", "보정동"], ["seongnam"]),
    ("suji-gu-office-station", "수지구청역", "yongin", ["신분당선"], ["풍덕천동", "동천동"], []),
    ("seongbok-station", "성복역", "yongin", ["신분당선"], ["성복동", "상현동"], []),
    ("sanghyeon-station", "상현역", "yongin", ["신분당선"], ["상현동", "성복동"], ["suwon"]),
    ("giheung-station", "기흥역", "yongin", ["수인분당선", "용인에버라인"], ["구갈동", "신갈동"], ["suwon"]),
    ("dongbaek-station", "동백역", "yongin", ["용인에버라인"], ["동백동", "중동"], []),
    ("bojeong-station", "보정역", "yongin", ["수인분당선"], ["보정동", "죽전동"], []),
    ("dongtan-station", "동탄역", "hwaseong", ["SRT", "GTX-A"], ["반송동", "오산동"], ["osan"]),
    ("byeongjeom-station", "병점역", "hwaseong", ["1호선"], ["병점동", "진안동"], ["suwon"]),
    ("bucheon-station", "부천역", "bucheon", ["1호선"], ["심곡동", "소사동"], []),
    ("songnae-station", "송내역", "bucheon", ["1호선"], ["송내동", "중동"], []),
    ("yeokgok-station", "역곡역", "bucheon", ["1호선"], ["역곡동", "소사동"], []),
    ("bucheon-city-hall-station", "부천시청역", "bucheon", ["7호선"], ["중동", "상동"], []),
    ("sangdong-station", "상동역", "bucheon", ["7호선"], ["상동", "중동"], []),
    ("jungang-station", "중앙역", "ansan", ["4호선", "수인분당선"], ["고잔동", "중앙동"], []),
    ("choji-station", "초지역", "ansan", ["4호선", "수인분당선", "서해선"], ["초지동", "원곡동"], ["siheung"]),
    ("ansan-station", "안산역", "ansan", ["4호선"], ["원곡동", "신길동"], ["siheung"]),
    ("sangnoksu-station", "상록수역", "ansan", ["4호선"], ["본오동", "이동"], []),
    ("anyang-station", "안양역", "anyang", ["1호선"], ["안양동", "만안구"], []),
    ("beomgye-station", "범계역", "anyang", ["4호선"], ["범계동", "호계동", "평촌동"], []),
    ("pyeongchon-station", "평촌역", "anyang", ["4호선"], ["평촌동", "관양동"], []),
    ("indeogwon-station", "인덕원역", "anyang", ["4호선", "GTX-C"], ["관양동", "포일동"], ["uiwang", "gwacheon"]),
    ("oido-station", "오이도역", "siheung", ["4호선", "수인분당선"], ["정왕동", "오이도"], ["ansan"]),
    ("jeongwang-station", "정왕역", "siheung", ["4호선"], ["정왕동", "배곧동"], []),
    ("siheung-city-hall-station", "시흥시청역", "siheung", ["서해선", "소사원시선"], ["장현동", "능곡동"], []),
    ("pyeongtaek-station", "평택역", "pyeongtaek", ["1호선"], ["평택동", "비전동"], []),
    ("pyeongtaek-jije-station", "평택지제역", "pyeongtaek", ["1호선", "SRT"], ["고덕동", "지제동"], []),
    ("seojeongri-station", "서정리역", "pyeongtaek", ["1호선"], ["서정동", "송탄동"], []),
    ("gurae-station", "구래역", "gimpo", ["김포골드라인"], ["구래동", "마산동"], []),
    ("janggi-station", "장기역", "gimpo", ["김포골드라인"], ["장기동", "운양동"], []),
    ("pungmu-station", "풍무역", "gimpo", ["김포골드라인"], ["풍무동", "사우동"], []),
    ("daehwa-station", "대화역", "goyang", ["3호선"], ["대화동", "주엽동"], []),
    ("jeongbalsan-station", "정발산역", "goyang", ["3호선"], ["장항동", "마두동"], []),
    ("juyeop-station", "주엽역", "goyang", ["3호선"], ["주엽동", "대화동"], []),
    ("hwajeong-station", "화정역", "goyang", ["3호선"], ["화정동", "행신동"], []),
    ("samsong-station", "삼송역", "goyang", ["3호선"], ["삼송동", "원흥동"], []),
    ("uijeongbu-station", "의정부역", "uijeongbu", ["1호선", "의정부경전철"], ["의정부동", "가능동"], []),
    ("hoeryong-station", "회룡역", "uijeongbu", ["1호선", "의정부경전철"], ["호원동", "신곡동"], []),
    ("tapseok-station", "탑석역", "uijeongbu", ["의정부경전철"], ["민락동", "고산동"], []),
    ("dasan-station", "다산역", "namyangju", ["8호선"], ["다산동", "도농동"], ["guri"]),
    ("byeollae-station", "별내역", "namyangju", ["경춘선", "8호선"], ["별내동"], ["guri"]),
    ("pyeongnae-hopyeong-station", "평내호평역", "namyangju", ["경춘선"], ["평내동", "호평동"], []),
    ("maseok-station", "마석역", "namyangju", ["경춘선"], ["화도읍", "마석"], ["gapyeong"]),
    ("unjeong-station", "운정역", "paju", ["경의중앙선"], ["야당동", "와동동"], []),
    ("geumchon-station", "금촌역", "paju", ["경의중앙선"], ["금촌동", "아동동"], []),
    ("guri-station", "구리역", "guri", ["경의중앙선", "경춘선"], ["인창동", "수택동"], ["namyangju"]),
    ("galmae-station", "갈매역", "guri", ["경춘선"], ["갈매동"], ["namyangju"]),
    ("misa-station", "미사역", "hanam", ["5호선"], ["풍산동", "망월동"], []),
    ("hanam-pungsan-station", "하남풍산역", "hanam", ["5호선"], ["덕풍동", "신장동"], []),
    ("hanam-geomdansan-station", "하남검단산역", "hanam", ["5호선"], ["창우동", "신장동"], []),
    ("cheolsan-station", "철산역", "gwangmyeong", ["7호선"], ["철산동", "광명동"], []),
    ("gwangmyeong-sageori-station", "광명사거리역", "gwangmyeong", ["7호선"], ["광명동", "하안동"], []),
    ("gwangmyeong-station", "광명역", "gwangmyeong", ["KTX", "1호선"], ["일직동", "소하동"], []),
    ("sanbon-station", "산본역", "gunpo", ["4호선"], ["산본동", "금정동"], []),
    ("geumjeong-station", "금정역", "gunpo", ["1호선", "4호선", "GTX-C"], ["금정동", "당정동"], ["anyang"]),
    ("osan-station", "오산역", "osan", ["1호선"], ["중앙동", "오산동"], []),
    ("osan-university-station", "오산대역", "osan", ["1호선"], ["세교동", "수청동"], []),
    ("uiwang-station", "의왕역", "uiwang", ["1호선"], ["부곡동", "삼동"], []),
    ("gwacheon-station", "과천역", "gwacheon", ["4호선"], ["중앙동", "별양동"], []),
    ("gwacheon-government-complex-station", "정부과천청사역", "gwacheon", ["4호선"], ["별양동", "부림동"], []),
    ("gwangju-station", "경기광주역", "gwangju-si", ["경강선"], ["경안동", "역동"], []),
    ("gonjiam-station", "곤지암역", "gwangju-si", ["경강선"], ["곤지암읍"], []),
    ("icheon-station", "이천역", "icheon", ["경강선"], ["창전동", "증포동"], []),
    ("bubal-station", "부발역", "icheon", ["경강선"], ["부발읍"], []),
    ("yangpyeong-station", "양평역", "yangpyeong", ["경의중앙선"], ["양평읍"], []),
    ("yongmun-station", "용문역", "yangpyeong", ["경의중앙선"], ["용문면"], []),
    ("yeoju-station", "여주역", "yeoju", ["경강선"], ["여주동", "교동"], []),
    ("yangju-station", "양주역", "yangju", ["1호선"], ["덕정동", "회천동"], []),
    ("deokjeong-station", "덕정역", "yangju", ["1호선"], ["덕정동", "옥정동"], []),
    ("dongducheon-jungang-station", "동두천중앙역", "dongducheon", ["1호선"], ["생연동", "지행동"], []),
    ("jihaeng-station", "지행역", "dongducheon", ["1호선"], ["지행동", "송내동"], []),
    ("gapyeong-station", "가평역", "gapyeong", ["경춘선"], ["가평읍"], []),
    ("cheongpyeong-station", "청평역", "gapyeong", ["경춘선"], ["청평면"], []),
    ("jeongok-station", "전곡역", "yeoncheon", ["1호선"], ["전곡읍"], []),
]


# ===== 대표 읍면동 (개별 페이지 생성 대상, 1차 핵심) =====
# slug, name, city(slug), gu(slug or None), nearby_stations(역명), nearby_dong(동명)
DONG_PAGES = [
    # 수원
    ("ingye-dong", "인계동", "suwon", "paldal-gu", ["수원시청역", "매교역"], ["매산동", "권선동", "우만동"]),
    ("maesan-dong", "매산동", "suwon", "paldal-gu", ["수원역", "매교역"], ["인계동", "고등동", "세류동"]),
    ("yeongtong-dong", "영통동", "suwon", "yeongtong-gu", ["영통역", "망포역"], ["망포동", "매탄동", "원천동"]),
    ("mangpo-dong", "망포동", "suwon", "yeongtong-gu", ["망포역", "영통역"], ["영통동", "매탄동"]),
    ("gwanggyo-dong", "광교동", "suwon", "yeongtong-gu", ["광교중앙역"], ["원천동", "영통동"]),
    # 성남
    ("jeongja-dong-seongnam", "정자동", "seongnam", "bundang-gu", ["정자역", "수내역"], ["수내동", "서현동"]),
    ("seohyeon-dong", "서현동", "seongnam", "bundang-gu", ["서현역"], ["이매동", "수내동"]),
    ("sunae-dong", "수내동", "seongnam", "bundang-gu", ["수내역", "정자역"], ["정자동", "서현동"]),
    ("yatap-dong", "야탑동", "seongnam", "bundang-gu", ["야탑역"], ["이매동", "서현동"]),
    ("pangyo-dong", "판교동", "seongnam", "bundang-gu", ["판교역"], ["백현동", "삼평동"]),
    ("baekhyeon-dong", "백현동", "seongnam", "bundang-gu", ["판교역"], ["판교동", "삼평동"]),
    # 용인
    ("jukjeon-dong", "죽전동", "yongin", "suji-gu", ["죽전역", "보정역"], ["보정동", "풍덕천동"]),
    ("dongcheon-dong", "동천동", "yongin", "suji-gu", ["동천역", "수지구청역"], ["성복동", "풍덕천동"]),
    ("seongbok-dong", "성복동", "yongin", "suji-gu", ["성복역", "상현역"], ["상현동", "동천동"]),
    ("sanghyeon-dong", "상현동", "yongin", "suji-gu", ["상현역", "성복역"], ["성복동", "풍덕천동"]),
    ("dongbaek-dong", "동백동", "yongin", "giheung-gu", ["동백역"], ["중동", "구갈동"]),
    ("guhal-dong", "구갈동", "yongin", "giheung-gu", ["기흥역"], ["신갈동", "동백동"]),
    ("bojeong-dong", "보정동", "yongin", "giheung-gu", ["보정역", "죽전역"], ["죽전동", "마북동"]),
    # 고양
    ("janghang-dong", "장항동", "goyang", "ilsandong-gu", ["정발산역", "마두역"], ["마두동", "백석동"]),
    ("madu-dong", "마두동", "goyang", "ilsandong-gu", ["마두역", "정발산역"], ["장항동", "백석동"]),
    ("baekseok-dong", "백석동", "goyang", "ilsandong-gu", ["백석역"], ["마두동", "장항동"]),
    ("juyeop-dong", "주엽동", "goyang", "ilsanseo-gu", ["주엽역", "대화역"], ["대화동", "일산동"]),
    ("daehwa-dong", "대화동", "goyang", "ilsanseo-gu", ["대화역"], ["주엽동", "탄현동"]),
    ("hwajeong-dong", "화정동", "goyang", "deogyang-gu", ["화정역"], ["행신동", "삼송동"]),
    ("samsong-dong", "삼송동", "goyang", "deogyang-gu", ["삼송역"], ["원흥동", "화정동"]),
    # 부천
    ("jung-dong-bucheon", "중동", "bucheon", "wonmi-gu", ["신중동역", "부천시청역"], ["상동", "심곡동"]),
    ("sangdong-bucheon", "상동", "bucheon", "wonmi-gu", ["상동역", "부천시청역"], ["중동", "송내동"]),
    ("songnae-dong", "송내동", "bucheon", "sosa-gu", ["송내역"], ["중동", "역곡동"]),
    ("yeokgok-dong", "역곡동", "bucheon", "sosa-gu", ["역곡역"], ["소사본동", "송내동"]),
    # 안산
    ("gojan-dong", "고잔동", "ansan", "danwon-gu", ["중앙역", "고잔역"], ["중앙동", "초지동"]),
    ("choji-dong", "초지동", "ansan", "danwon-gu", ["초지역"], ["고잔동", "원곡동"]),
    ("bono-dong", "본오동", "ansan", "sangnok-gu", ["상록수역"], ["사동", "이동"]),
    # 안양
    ("pyeongchon-dong", "평촌동", "anyang", "dongan-gu", ["평촌역", "범계역"], ["호계동", "관양동"]),
    ("hogye-dong", "호계동", "anyang", "dongan-gu", ["범계역"], ["평촌동", "비산동"]),
    ("anyang-dong", "안양동", "anyang", "manan-gu", ["안양역", "명학역"], ["석수동", "박달동"]),
    # 일반구 없는 도시
    ("dongtan-area", "동탄", "hwaseong", None, ["동탄역"], ["반송동", "청계동"]),
    ("byeongjeom-dong", "병점동", "hwaseong", None, ["병점역"], ["진안동", "봉담읍"]),
    ("hyangnam-eup", "향남읍", "hwaseong", None, [], ["남양읍", "봉담읍"]),
    ("baegot-dong", "배곧동", "siheung", None, ["정왕역"], ["정왕동"]),
    ("jeongwang-dong", "정왕동", "siheung", None, ["정왕역", "오이도역"], ["배곧동"]),
    ("gurae-dong", "구래동", "gimpo", None, ["구래역"], ["마산동", "장기동"]),
    ("janggi-dong", "장기동", "gimpo", None, ["장기역", "운양역"], ["운양동", "구래동"]),
    ("dasan-dong", "다산동", "namyangju", None, ["다산역", "도농역"], ["별내동"]),
    ("byeollae-dong", "별내동", "namyangju", None, ["별내역"], ["다산동"]),
    ("jinjeop-eup", "진접읍", "namyangju", None, ["진접역"], ["오남읍"]),
    ("uijeongbu-dong", "의정부동", "uijeongbu", None, ["의정부역"], ["가능동", "호원동"]),
    ("minrak-dong", "민락동", "uijeongbu", None, ["탑석역"], ["신곡동", "고산동"]),
    ("misa-area", "미사", "hanam", None, ["미사역", "하남풍산역"], ["풍산동", "덕풍동"]),
    ("cheolsan-dong", "철산동", "gwangmyeong", None, ["철산역"], ["광명동", "하안동"]),
    ("sanbon-dong", "산본동", "gunpo", None, ["산본역"], ["금정동", "당정동"]),
]
